on:
  release
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, edited]
name: Build and Publish
jobs:
  buildAndPublish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Install Dependencies
      uses: cedrickring/golang-action@1.3.0
      with:
        entrypoint: make
        args: dep
    
    - name: Build
      uses: cedrickring/golang-action@1.3.0
      with:
        entrypoint: make
        args: build
    
    - name: Publish
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'bin/okteto-*'
