on:
  release
    types: [published, edited]
name: Build and Publish
jobs:
  buildAndPublish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: InstallDep
      uses: cedrickring/golang-action@1.3.0
      with:
        entrypoint: make
        args: dep
    
    - name: Build
      uses: cedrickring/golang-action@1.3.0
      with:
        entrypoint: make
        args: build
        
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: bins
        path: ./bin
    
    - name: Publish
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'bin/okteto-*'
